// projects/ui/lit/avatar.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppAvatar = class AppAvatar extends LitElement {
    src = null;
    name = "";
    size = "md";
    shape = "circle";
    static styles = css `
    :host {
      display: inline-flex;
    }

    .app-avatar {
      @apply inline-flex items-center justify-center overflow-hidden bg-[var(--bg-tertiary)] text-[var(--text-secondary)] font-medium;
    }

    .app-avatar-xs {
      @apply w-6 h-6 text-xs;
    }

    .app-avatar-sm {
      @apply w-8 h-8 text-sm;
    }

    .app-avatar-md {
      @apply w-10 h-10 text-base;
    }

    .app-avatar-lg {
      @apply w-12 h-12 text-lg;
    }

    .app-avatar-xl {
      @apply w-16 h-16 text-xl;
    }

    .app-avatar-circle {
      @apply rounded-full;
    }

    .app-avatar-square {
      border-radius: 0;
    }

    .app-avatar-rounded {
      @apply rounded-lg;
    }

    .app-avatar-img {
      @apply w-full h-full object-cover;
    }

    .app-avatar-initials {
      @apply w-full h-full flex items-center justify-center;
    }
  `;
    get initials() {
        if (!this.name)
            return "?";
        const parts = this.name.trim().split(/\s+/);
        if (parts.length === 1)
            return parts[0].charAt(0).toUpperCase();
        return (parts[0].charAt(0) + parts[parts.length - 1].charAt(0)).toUpperCase();
    }
    render() {
        const classes = [
            "app-avatar",
            `app-avatar-${this.size}`,
            `app-avatar-${this.shape}`,
        ].join(" ");
        return html `
      <span class="${classes}">
        ${this.src
            ? html `<img
              src="${this.src}"
              alt="${this.name}"
              class="app-avatar-img"
            />`
            : html `<span class="app-avatar-initials">${this.initials}</span>`}
      </span>
    `;
    }
};
__decorate([
    property()
], AppAvatar.prototype, "src", void 0);
__decorate([
    property()
], AppAvatar.prototype, "name", void 0);
__decorate([
    property()
], AppAvatar.prototype, "size", void 0);
__decorate([
    property()
], AppAvatar.prototype, "shape", void 0);
AppAvatar = __decorate([
    customElement("app-avatar")
], AppAvatar);
export { AppAvatar };
//# sourceMappingURL=avatar.js.map

// projects/shared/src/components/avatar/avatar.component.ts
import { Component, Input } from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-avatar",
  standalone: true,
  template: `
    @if (src && !imgError) {
      <img [src]="src" [alt]="alt" (error)="imgError = true" />
    } @else {
      <span class="initials">{{ initials }}</span>
    }
  `,
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        border-radius: 50%;
        overflow: hidden;
        background-color: var(--bg-elevated);
        border: 1px solid var(--border-color);
      }
      :host([size="sm"]) {
        width: 2rem;
        height: 2rem;
        font-size: 0.75rem;
      }
      :host([size="md"]) {
        width: 2.5rem;
        height: 2.5rem;
        font-size: 0.875rem;
      }
      :host([size="lg"]) {
        width: 3.5rem;
        height: 3.5rem;
        font-size: 1.25rem;
      }
      img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
      .initials {
        font-weight: 600;
        color: var(--text-secondary);
        text-transform: uppercase;
      }
    `,
  ],
})
export class AvatarComponent {
  @Input() src = "";
  @Input() alt = "";
  @Input() size: "sm" | "md" | "lg" = "md";
  imgError = false;

  get initials(): string {
    return (this.alt || "").substring(0, 2).toUpperCase();
  }
}

registerSchemaComponent("app-avatar", AvatarComponent);

<div appApplyTheme="app-avatar">
  @if (src && !imgError) {
    <img
      class="w-full h-full object-cover"
      [src]="src"
      [alt]="alt"
      (error)="imgError = true"
    />
  } @else {
    <span class="font-semibold text-[var(--text-secondary)] uppercase">{{
      initials
    }}</span>
  }
</div>
