// projects/ui/lit/pagination.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppPagination = class AppPagination extends LitElement {
  constructor() {
    super(...arguments);
    this.totalItems = 0;
    this.currentPage = 1;
    this.pageSize = 10;
  }
  static {
    this.styles = css`
      :host {
        display: block;
      }

      .app-pagination {
        display: flex;
        align-items: center;
        gap: 0.25rem;
      }

      .app-pagination-btn {
        width: 2rem;
        height: 2rem;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 0.5rem;
        color: var(--text-secondary);
        background: transparent;
        border: none;
        cursor: pointer;
        transition: background-color 0.15s;
      }
      .app-pagination-btn:hover {
        background-color: var(--bg-hover);
      }

      .app-pagination-btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .app-pagination-btn i {
        font-size: 1.25rem;
      }

      .app-pagination-page {
        min-width: 2rem;
        height: 2rem;
        padding: 0 0.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 0.5rem;
        font-size: 0.875rem;
        color: var(--text-secondary);
        background: transparent;
        border: none;
        cursor: pointer;
        transition: background-color 0.15s;
      }
      .app-pagination-page:hover {
        background-color: var(--bg-hover);
      }

      .app-pagination-page-active {
        background-color: var(--accent);
        color: var(--text-on-accent);
      }
      .app-pagination-page-active:hover {
        background-color: var(--accent);
      }

      .app-pagination-ellipsis {
        padding: 0 0.25rem;
        color: var(--text-muted);
      }
    `;
  }
  get totalPages() {
    return Math.ceil(this.totalItems / this.pageSize);
  }
  get visiblePages() {
    const pages = [];
    const total = this.totalPages;
    const current = this.currentPage;
    if (total <= 7) {
      for (let i = 1; i <= total; i++) pages.push(i);
    } else {
      pages.push(1);
      if (current > 3) pages.push(-1);
      for (
        let i = Math.max(2, current - 1);
        i <= Math.min(total - 1, current + 1);
        i++
      ) {
        pages.push(i);
      }
      if (current < total - 2) pages.push(-1);
      pages.push(total);
    }
    return pages;
  }
  _goToPage(page) {
    if (page < 1 || page > this.totalPages || page === this.currentPage) return;
    this.currentPage = page;
    this.dispatchEvent(
      new CustomEvent("page-change", {
        detail: page,
        bubbles: true,
        composed: true,
      }),
    );
  }
  _previous() {
    this._goToPage(this.currentPage - 1);
  }
  _next() {
    this._goToPage(this.currentPage + 1);
  }
  _isEllipsis(page) {
    return page === -1;
  }
  render() {
    return html`
      <div class="app-pagination">
        <button
          class="app-pagination-btn"
          ?disabled="${this.currentPage === 1}"
          @click="${this._previous}"
        >
          <i class="material-icons">chevron_left</i>
        </button>

        ${this.visiblePages.map((page) =>
          this._isEllipsis(page)
            ? html`<span class="app-pagination-ellipsis">...</span>`
            : html`
                <button
                  class="app-pagination-page ${page === this.currentPage
                    ? "app-pagination-page-active"
                    : ""}"
                  @click="${() => this._goToPage(page)}"
                >
                  ${page}
                </button>
              `,
        )}

        <button
          class="app-pagination-btn"
          ?disabled="${this.currentPage === this.totalPages}"
          @click="${this._next}"
        >
          <i class="material-icons">chevron_right</i>
        </button>
      </div>
    `;
  }
};
__decorate(
  [property({ type: Number })],
  AppPagination.prototype,
  "totalItems",
  void 0,
);
__decorate(
  [property({ type: Number })],
  AppPagination.prototype,
  "currentPage",
  void 0,
);
__decorate(
  [property({ type: Number })],
  AppPagination.prototype,
  "pageSize",
  void 0,
);
AppPagination = __decorate([customElement("app-pagination")], AppPagination);
export { AppPagination };
//# sourceMappingURL=pagination.js.map

// projects/shared/src/components/pagination/pagination.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  computed,
} from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-pagination",
  standalone: true,
  template: `
    <div class="pagination">
      <button [disabled]="page <= 1" (click)="goTo(page - 1)">&laquo;</button>
      @for (p of visiblePages; track p) {
        @if (p === "...") {
          <span class="ellipsis">&hellip;</span>
        } @else {
          <button [class.active]="p === page" (click)="goTo(+p)">
            {{ p }}
          </button>
        }
      }
      <button [disabled]="page >= totalPages" (click)="goTo(page + 1)">
        &raquo;
      </button>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
      .pagination {
        display: inline-flex;
        align-items: center;
        gap: 0.25rem;
      }
      button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        min-width: 2rem;
        height: 2rem;
        padding: 0 0.5rem;
        border: 1px solid var(--border-color);
        border-radius: 0.375rem;
        background-color: var(--bg-elevated);
        color: var(--text-primary);
        font-size: 0.875rem;
        cursor: pointer;
        transition: background-color 0.15s;
      }
      button:hover:not(:disabled) {
        background-color: var(--bg-hover);
      }
      button:disabled {
        opacity: 0.4;
        cursor: not-allowed;
      }
      button.active {
        background-color: var(--accent);
        border-color: var(--accent);
        color: var(--text-on-accent);
      }
      .ellipsis {
        padding: 0 0.25rem;
        color: var(--text-secondary);
      }
    `,
  ],
})
export class PaginationComponent {
  @Input() page = 1;
  @Input() total = 1;
  @Input() pageSize = 10;
  @Output() pageChanged = new EventEmitter<number>();

  get totalPages(): number {
    return Math.max(1, Math.ceil(this.total / this.pageSize));
  }

  get visiblePages(): (number | string)[] {
    const tp = this.totalPages;
    if (tp <= 7) return Array.from({ length: tp }, (_, i) => i + 1);
    const pages: (number | string)[] = [];
    if (this.page <= 4) {
      for (let i = 1; i <= 5; i++) pages.push(i);
      pages.push("...", tp);
    } else if (this.page >= tp - 3) {
      pages.push(1, "...");
      for (let i = tp - 4; i <= tp; i++) pages.push(i);
    } else {
      pages.push(1, "...");
      for (let i = this.page - 1; i <= this.page + 1; i++) pages.push(i);
      pages.push("...", tp);
    }
    return pages;
  }

  goTo(p: number) {
    if (p < 1 || p > this.totalPages || p === this.page) return;
    this.page = p;
    this.pageChanged.emit(p);
  }
}

registerSchemaComponent("app-pagination", PaginationComponent);

<div
  class="flex w-full items-center justify-between border-t border-[var(--border-subtle)] bg-transparent px-6 py-3"
>
  <div class="flex items-center gap-6">
    <span class="text-sm text-[var(--text-dim)]">
      Showing
      <span class="font-bold text-[var(--text-main)]">{{ startIndex }}</span
      >-<span class="font-bold text-[var(--text-main)]">{{ endIndex }}</span> of
      <span class="font-bold text-[var(--text-main)]">{{ totalItems }}</span>
    </span>
    <div class="flex items-center gap-3">
      <span class="text-xs text-[var(--text-muted)]">Rows per page:</span>
      <select
        class="cursor-pointer rounded-lg border border-[var(--border-visible)] bg-[var(--bg-card)] px-3 py-1.5 text-sm text-[var(--text-main)] focus:border-[var(--accent)] focus:outline-none"
        [value]="pageSize"
        (change)="onPageSizeChange(+$any($event.target).value)"
      >
        <option value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
      </select>
    </div>
  </div>

  <div class="flex items-center gap-2">
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasPrevPage"
      (click)="firstPage()"
      title="First page"
    >
      <app-icon icon="first_page" [size]="18" />
    </button>
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasPrevPage"
      (click)="prevPage()"
      title="Previous page"
    >
      <app-icon icon="chevron_left" [size]="18" />
    </button>
    <span class="px-3 text-sm text-[var(--text-dim)]"
      >Page {{ currentPage + 1 }} of {{ totalPages || 1 }}</span
    >
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasNextPage"
      (click)="nextPage()"
      title="Next page"
    >
      <app-icon icon="chevron_right" [size]="18" />
    </button>
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasNextPage"
      (click)="lastPage()"
      title="Last page"
    >
      <app-icon icon="last_page" [size]="18" />
    </button>
  </div>
</div>
