// projects/ui/lit/checkbox.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppCheckbox = class AppCheckbox extends LitElement {
  constructor() {
    super(...arguments);
    this.label = "";
    this.disabled = false;
    this.checked = false;
    this.indeterminate = false;
  }
  static {
    this.styles = css`
      :host {
        display: inline-flex;
      }

      .app-checkbox {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        cursor: pointer;
      }

      .app-checkbox-disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .app-checkbox-box {
        width: 1.25rem;
        height: 1.25rem;
        border-radius: 0.25rem;
        border: 2px solid var(--border-color);
        display: flex;
        align-items: center;
        justify-content: center;
        transition: all 0.15s;
        box-sizing: border-box;
      }

      .app-checkbox-unchecked {
        background-color: transparent;
        border-color: var(--border-color);
      }

      .app-checkbox-checked {
        background-color: var(--accent);
        border-color: var(--accent);
        color: var(--text-on-accent);
      }

      .app-checkbox-indeterminate {
        background-color: var(--accent);
        border-color: var(--accent);
        color: var(--text-on-accent);
      }

      .app-checkbox-box i {
        font-size: 0.875rem;
      }

      .app-checkbox-label {
        color: var(--text-primary);
        font-size: 0.875rem;
      }
    `;
  }
  get state() {
    if (this.indeterminate) return "indeterminate";
    return this.checked ? "checked" : "unchecked";
  }
  _handleClick() {
    if (this.disabled) return;
    const newChecked = !this.checked;
    this.checked = newChecked;
    this.dispatchEvent(
      new CustomEvent("checked-change", {
        detail: newChecked,
        bubbles: true,
        composed: true,
      }),
    );
  }
  render() {
    const classes = ["app-checkbox-box", `app-checkbox-${this.state}`].join(
      " ",
    );
    return html`
      <label
        class="app-checkbox ${this.disabled ? "app-checkbox-disabled" : ""}"
      >
        <span class="${classes}" @click="${this._handleClick}">
          ${this.state === "checked"
            ? html`<i class="material-icons">check</i>`
            : this.state === "indeterminate"
              ? html`<i class="material-icons">remove</i>`
              : ""}
        </span>
        ${this.label
          ? html`<span class="app-checkbox-label">${this.label}</span>`
          : ""}
      </label>
    `;
  }
};
__decorate([property()], AppCheckbox.prototype, "label", void 0);
__decorate(
  [property({ type: Boolean })],
  AppCheckbox.prototype,
  "disabled",
  void 0,
);
__decorate(
  [property({ type: Boolean })],
  AppCheckbox.prototype,
  "checked",
  void 0,
);
__decorate(
  [property({ type: Boolean })],
  AppCheckbox.prototype,
  "indeterminate",
  void 0,
);
AppCheckbox = __decorate([customElement("app-checkbox")], AppCheckbox);
export { AppCheckbox };
//# sourceMappingURL=checkbox.js.map

// projects/shared/src/components/checkbox/checkbox.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-checkbox",
  standalone: true,
  template: `
    <label>
      <input
        type="checkbox"
        [checked]="checked"
        [disabled]="disabled"
        (change)="handleChange($event)"
      />
      @if (label) {
        <span class="checkbox-label">{{ label }}</span>
      }
    </label>
  `,
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
      }
      label {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        cursor: pointer;
      }
      input[type="checkbox"] {
        width: 1rem;
        height: 1rem;
        accent-color: var(--accent);
        cursor: pointer;
      }
      input[type="checkbox"]:disabled {
        cursor: not-allowed;
        opacity: 0.5;
      }
      .checkbox-label {
        color: var(--text-primary);
        font-size: 0.875rem;
        user-select: none;
      }
    `,
  ],
})
export class CheckboxComponent {
  @Input() checked = false;
  @Input() label = "";
  @Input() disabled = false;
  @Output() changed = new EventEmitter<boolean>();

  handleChange(e: Event) {
    this.changed.emit((e.target as HTMLInputElement).checked);
  }
}

registerSchemaComponent("app-checkbox", CheckboxComponent);

<label
  appApplyTheme="app-checkbox"
  class="flex items-center gap-2 cursor-pointer"
>
  <input
    type="checkbox"
    class="w-4 h-4"
    [style.accent-color]="'var(--accent)'"
    [checked]="checked"
    [disabled]="disabled"
    (change)="handleChange($event)"
  />
  @if (label) {
    <span class="text-sm select-none text-[var(--text-primary)]">{{
      label
    }}</span>
  }
</label>
