// projects/ui/lit/chip.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppChip = class AppChip extends LitElement {
    label = "";
    icon = null;
    removable = false;
    selected = false;
    static styles = css `
    :host {
      display: inline-flex;
    }

    .app-chip {
      @apply inline-flex items-center gap-1 px-3 py-1.5 rounded-full text-sm font-medium;
      @apply bg-[var(--bg-tertiary)] text-[var(--text-secondary)] border border-transparent;
      @apply transition-all cursor-pointer;
    }

    .app-chip:hover {
      @apply bg-[var(--bg-hover)];
    }

    .app-chip-selected {
      @apply bg-[var(--accent-100)] text-[var(--accent-700)] border-[var(--accent)];
    }

    .app-chip-icon {
      @apply text-base;
    }

    .app-chip-label {
      @apply text-inherit;
    }

    .app-chip-remove {
      @apply ml-1 p-0.5 rounded-full hover:bg-black/10 transition-colors;
      @apply flex items-center justify-center;
      background: transparent;
      border: none;
      cursor: pointer;
      padding: 0;
    }

    .app-chip-remove i {
      @apply text-xs;
    }
  `;
    _handleRemove(e) {
        e.stopPropagation();
        this.dispatchEvent(new CustomEvent("remove", { bubbles: true, composed: true }));
    }
    _handleClick() {
        this.selected = !this.selected;
        this.dispatchEvent(new CustomEvent("selected-change", {
            detail: this.selected,
            bubbles: true,
            composed: true,
        }));
    }
    render() {
        const classes = ["app-chip", this.selected ? "app-chip-selected" : ""].join(" ");
        return html `
      <span class="${classes}" @click="${this._handleClick}">
        ${this.icon
            ? html `<i class="material-icons app-chip-icon">${this.icon}</i>`
            : ""}
        <span class="app-chip-label">${this.label}</span>
        ${this.removable
            ? html `
              <button class="app-chip-remove" @click="${this._handleRemove}">
                <i class="material-icons">close</i>
              </button>
            `
            : ""}
      </span>
    `;
    }
};
__decorate([
    property()
], AppChip.prototype, "label", void 0);
__decorate([
    property()
], AppChip.prototype, "icon", void 0);
__decorate([
    property({ type: Boolean })
], AppChip.prototype, "removable", void 0);
__decorate([
    property({ type: Boolean })
], AppChip.prototype, "selected", void 0);
AppChip = __decorate([
    customElement("app-chip")
], AppChip);
export { AppChip };
//# sourceMappingURL=chip.js.map

// projects/shared/src/components/chip/chip.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { MatIconModule } from "@angular/material/icon";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-chip",
  standalone: true,
  imports: [MatIconModule],
  template: `
    <span class="chip">
      @if (icon) {
        <mat-icon class="chip-icon" [fontIcon]="icon" />
      }
      <span>{{ label }}</span>
      @if (removable) {
        <button
          class="remove-btn"
          (click)="handleRemove($event)"
          aria-label="Remove"
        >
          &times;
        </button>
      }
    </span>
  `,
  styles: [
    `
      :host {
        display: inline-flex;
      }
      .chip {
        display: inline-flex;
        align-items: center;
        gap: 0.375rem;
        padding: 0.25rem 0.75rem;
        border-radius: 1rem;
        background-color: var(--bg-elevated);
        border: 1px solid var(--border-color);
        color: var(--text-primary);
        font-size: 0.875rem;
        font-weight: 500;
        transition: background-color 0.15s;
      }
      .chip:hover {
        background-color: var(--bg-hover);
      }
      .chip-icon {
        font-size: 1rem;
      }
      .remove-btn {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 1rem;
        height: 1rem;
        padding: 0;
        border: none;
        background: transparent;
        color: var(--text-secondary);
        cursor: pointer;
        border-radius: 50%;
        transition: background-color 0.15s;
        margin-left: 0.125rem;
      }
      .remove-btn:hover {
        background-color: var(--border-color);
        color: var(--text-primary);
      }
    `,
  ],
})
export class ChipComponent {
  @Input() label = "";
  @Input() icon = "";
  @Input() removable = false;
  @Output() removed = new EventEmitter<void>();

  handleRemove(e: Event) {
    e.stopPropagation();
    this.removed.emit();
  }
}

registerSchemaComponent("app-chip", ChipComponent);

<span
  appApplyTheme="app-chip"
  class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border text-sm font-medium transition-colors hover:bg-[var(--bg-hover)] bg-[var(--bg-elevated)] border-[var(--border-color)] text-[var(--text-primary)]"
>
  @if (icon) {
    <app-icon class="text-base" [icon]="icon" [size]="16" />
  }
  <span>{{ label }}</span>
  @if (removable || closeable) {
    <button
      class="inline-flex items-center justify-center w-4 h-4 p-0 border-0 bg-transparent rounded-full transition-colors ms-0.5 hover:bg-[var(--border-color)] hover:text-[var(--text-primary)] text-[var(--text-secondary)]"
      (click)="handleRemove($event)"
      aria-label="Remove"
    >
      &times;
    </button>
  }
</span>
