// projects/shared/src/ui/avatar/avatar.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import { CommonModule } from "@angular/common";

export type AvatarSize = "xs" | "sm" | "md" | "lg" | "xl";
export type AvatarShape = "circle" | "square" | "rounded";

@Component({
  selector: "app-avatar",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: "./avatar.component.html",
  styleUrl: "./avatar.component.css",
})
export class AvatarComponent {
  @Input() src: string | null = null;
  @Input() name: string = "";
  @Input() size: AvatarSize = "md";
  @Input() shape: AvatarShape = "circle";

  get initials(): string {
    if (!this.name) return "?";
    const parts = this.name.trim().split(/\s+/);
    if (parts.length === 1) return parts[0].charAt(0).toUpperCase();
    return (
      parts[0].charAt(0) + parts[parts.length - 1].charAt(0)
    ).toUpperCase();
  }

  get avatarClass(): string {
    const classes = [
      "app-avatar",
      `app-avatar-${this.size}`,
      `app-avatar-${this.shape}`,
    ];
    return classes.join(" ");
  }
}

// projects/ui/lit/avatar.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppAvatar = class AppAvatar extends LitElement {
    src = null;
    name = "";
    size = "md";
    shape = "circle";
    static styles = css `
    :host {
      display: inline-flex;
    }

    .app-avatar {
      @apply inline-flex items-center justify-center overflow-hidden bg-[var(--bg-tertiary)] text-[var(--text-secondary)] font-medium;
    }

    .app-avatar-xs {
      @apply w-6 h-6 text-xs;
    }

    .app-avatar-sm {
      @apply w-8 h-8 text-sm;
    }

    .app-avatar-md {
      @apply w-10 h-10 text-base;
    }

    .app-avatar-lg {
      @apply w-12 h-12 text-lg;
    }

    .app-avatar-xl {
      @apply w-16 h-16 text-xl;
    }

    .app-avatar-circle {
      @apply rounded-full;
    }

    .app-avatar-square {
      border-radius: 0;
    }

    .app-avatar-rounded {
      @apply rounded-lg;
    }

    .app-avatar-img {
      @apply w-full h-full object-cover;
    }

    .app-avatar-initials {
      @apply w-full h-full flex items-center justify-center;
    }
  `;
    get initials() {
        if (!this.name)
            return "?";
        const parts = this.name.trim().split(/\s+/);
        if (parts.length === 1)
            return parts[0].charAt(0).toUpperCase();
        return (parts[0].charAt(0) + parts[parts.length - 1].charAt(0)).toUpperCase();
    }
    render() {
        const classes = [
            "app-avatar",
            `app-avatar-${this.size}`,
            `app-avatar-${this.shape}`,
        ].join(" ");
        return html `
      <span class="${classes}">
        ${this.src
            ? html `<img
              src="${this.src}"
              alt="${this.name}"
              class="app-avatar-img"
            />`
            : html `<span class="app-avatar-initials">${this.initials}</span>`}
      </span>
    `;
    }
};
__decorate([
    property()
], AppAvatar.prototype, "src", void 0);
__decorate([
    property()
], AppAvatar.prototype, "name", void 0);
__decorate([
    property()
], AppAvatar.prototype, "size", void 0);
__decorate([
    property()
], AppAvatar.prototype, "shape", void 0);
AppAvatar = __decorate([
    customElement("app-avatar")
], AppAvatar);
export { AppAvatar };
//# sourceMappingURL=avatar.js.map
