// projects/shared/src/components/button/button.component.ts
import { Component, Input, Output, EventEmitter, inject } from "@angular/core";
import { MatIconModule } from "@angular/material/icon";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";
import { I18nService } from "../../core/lib/i18n/i18n.service";

export type ButtonStyle = "solid" | "outline" | "soft" | "ghost";
export type ButtonVariant =
  "primary" | "danger" | "warning" | "success" | "info";
export type ButtonSize = "sm" | "md" | "lg";

@Component({
  selector: "app-button",
  standalone: true,
  imports: [MatIconModule],
  template: `
    <button
      [attr.type]="type || 'button'"
      [class]="getButtonClass()"
      [disabled]="disabled || loading"
      (click)="handleClick($event)"
    >
      @if (loading) {
        <span class="app-btn-spinner"></span>
      } @else {
        @if (icon && iconPosition === "left") {
          <mat-icon class="app-btn-icon" [fontIcon]="icon" />
        }
        @if (label) {
          <span>{{ label }}</span>
        } @else {
          <ng-content></ng-content>
        }
        @if (icon && iconPosition === "right") {
          <mat-icon class="app-btn-icon" [fontIcon]="icon" />
        }
      }
    </button>
  `,
  styles: [
    `
      :host {
        display: inline-flex;
      }
      button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 0.5rem;
        border-radius: 0.5rem;
        border: 1px solid;
        padding: 0.5rem 1rem;
        text-align: center;
        font-weight: 500;
        transition: all 0.15s;
        cursor: pointer;
        border-width: 1px;
      }
      button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }
      .app-btn-solid {
        border-color: var(--accent);
        background-color: var(--accent);
        color: var(--text-on-accent);
      }
      .app-btn-solid:hover {
        background-color: var(--accent-hover);
        border-color: var(--accent-hover);
      }
      .app-btn-solid-danger {
        border-color: var(--error);
        background-color: var(--error);
        color: var(--text-on-error);
      }
      .app-btn-solid-danger:hover {
        opacity: 0.9;
      }
      .app-btn-solid-warning {
        border-color: var(--warning);
        background-color: var(--warning);
        color: var(--text-on-warning);
      }
      .app-btn-solid-warning:hover {
        opacity: 0.9;
      }
      .app-btn-solid-success {
        border-color: var(--success);
        background-color: var(--success);
        color: var(--text-on-success);
      }
      .app-btn-solid-success:hover {
        opacity: 0.9;
      }
      .app-btn-solid-info {
        border-color: var(--info);
        background-color: var(--info);
        color: var(--text-on-info);
      }
      .app-btn-solid-info:hover {
        opacity: 0.9;
      }
      .app-btn-outline {
        border-color: var(--accent);
        background-color: transparent;
        color: var(--accent);
      }
      .app-btn-outline:hover {
        background-color: color-mix(in srgb, var(--accent) 10%, transparent);
      }
      .app-btn-outline-danger {
        border-color: var(--error);
        background-color: transparent;
        color: var(--error);
      }
      .app-btn-outline-danger:hover {
        background-color: color-mix(in srgb, var(--error) 10%, transparent);
      }
      .app-btn-outline-warning {
        border-color: var(--warning);
        background-color: transparent;
        color: var(--warning);
      }
      .app-btn-outline-warning:hover {
        background-color: color-mix(in srgb, var(--warning) 10%, transparent);
      }
      .app-btn-outline-success {
        border-color: var(--success);
        background-color: transparent;
        color: var(--success);
      }
      .app-btn-outline-success:hover {
        background-color: color-mix(in srgb, var(--success) 10%, transparent);
      }
      .app-btn-outline-info {
        border-color: var(--info);
        background-color: transparent;
        color: var(--info);
      }
      .app-btn-outline-info:hover {
        background-color: color-mix(in srgb, var(--info) 10%, transparent);
      }
      .app-btn-soft {
        border-color: transparent;
        background-color: color-mix(in srgb, var(--accent) 10%, transparent);
        color: var(--accent);
      }
      .app-btn-soft:hover {
        background-color: color-mix(in srgb, var(--accent) 20%, transparent);
      }
      .app-btn-soft-danger {
        border-color: transparent;
        background-color: color-mix(in srgb, var(--error) 10%, transparent);
        color: var(--error);
      }
      .app-btn-soft-danger:hover {
        background-color: color-mix(in srgb, var(--error) 20%, transparent);
      }
      .app-btn-soft-warning {
        border-color: transparent;
        background-color: color-mix(in srgb, var(--warning) 10%, transparent);
        color: var(--warning);
      }
      .app-btn-soft-warning:hover {
        background-color: color-mix(in srgb, var(--warning) 20%, transparent);
      }
      .app-btn-soft-success {
        border-color: transparent;
        background-color: color-mix(in srgb, var(--success) 10%, transparent);
        color: var(--success);
      }
      .app-btn-soft-success:hover {
        background-color: color-mix(in srgb, var(--success) 20%, transparent);
      }
      .app-btn-soft-info {
        border-color: transparent;
        background-color: color-mix(in srgb, var(--info) 10%, transparent);
        color: var(--info);
      }
      .app-btn-soft-info:hover {
        background-color: color-mix(in srgb, var(--info) 20%, transparent);
      }
      .app-btn-ghost {
        border-color: transparent;
        background-color: transparent;
        color: var(--accent);
      }
      .app-btn-ghost:hover {
        background-color: color-mix(in srgb, var(--accent) 10%, transparent);
      }
      .app-btn-ghost-danger {
        border-color: transparent;
        background-color: transparent;
        color: var(--error);
      }
      .app-btn-ghost-danger:hover {
        background-color: color-mix(in srgb, var(--error) 10%, transparent);
      }
      .app-btn-ghost-warning {
        border-color: transparent;
        background-color: transparent;
        color: var(--warning);
      }
      .app-btn-ghost-warning:hover {
        background-color: color-mix(in srgb, var(--warning) 10%, transparent);
      }
      .app-btn-ghost-success {
        border-color: transparent;
        background-color: transparent;
        color: var(--success);
      }
      .app-btn-ghost-success:hover {
        background-color: color-mix(in srgb, var(--success) 10%, transparent);
      }
      .app-btn-ghost-info {
        border-color: transparent;
        background-color: transparent;
        color: var(--info);
      }
      .app-btn-ghost-info:hover {
        background-color: color-mix(in srgb, var(--info) 10%, transparent);
      }
      .app-btn-sm {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
      }
      .app-btn-md {
        padding: 0.5rem 1rem;
        font-size: 1rem;
      }
      .app-btn-lg {
        padding: 0.75rem 1.5rem;
        font-size: 1.125rem;
      }
      .app-btn-full {
        width: 100%;
      }
      .app-btn-disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }
      .app-btn-icon {
        font-size: 1.25rem;
      }
      .app-btn-spinner {
        width: 1rem;
        height: 1rem;
        border: 2px solid currentColor;
        border-top-color: transparent;
        border-radius: 50%;
        animation: spin 0.6s linear infinite;
      }
      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }
      .app-btn-primary {
        border-color: var(--accent);
        background-color: var(--accent);
        color: var(--text-on-accent);
      }
      .app-btn-primary:hover {
        background-color: var(--accent-hover);
        border-color: var(--accent-hover);
      }
      .app-btn-secondary {
        border-color: var(--border-color);
        background-color: var(--bg-elevated);
        color: var(--text-primary);
      }
      .app-btn-secondary:hover {
        background-color: var(--bg-hover);
      }
    `,
  ],
})
export class ButtonComponent {
  private i18n = inject(I18nService);

  @Input() variant: ButtonVariant = "primary";
  @Input() buttonStyle: ButtonStyle = "solid";
  @Input() size: ButtonSize = "md";
  @Input() disabled = false;
  @Input() loading = false;
  @Input() icon: string | null = null;
  @Input() iconPosition: "left" | "right" = "left";
  @Input() fullWidth = false;
  @Input() type: "button" | "submit" | "reset" = "button";
  @Input() label = "";
  @Input() set i18nKey(value: string | undefined) {
    if (value !== undefined && value !== null) {
      this.label = this.i18n.t(value);
    }
  }
  @Input() classes = "";
  @Input() ariaLabel = "";
  @Input() align = "";
  @Input() direction = "";
  @Input() height = "";
  @Input() justify = "";
  @Input() layout = "";
  @Input() width = "";

  @Output() clicked = new EventEmitter<MouseEvent>();

  handleClick(e: MouseEvent) {
    if (this.disabled || this.loading) {
      e.preventDefault();
      e.stopPropagation();
      return;
    }
    this.clicked.emit(e);
  }

  getButtonClass(): string {
    const style = this.buttonStyle || "solid";
    const variant = this.variant || "primary";
    const styleVariant =
      style === "solid" && variant === "primary"
        ? "app-btn-solid"
        : `app-btn-${style}${variant !== "primary" ? `-${variant}` : ""}`;
    return [
      "app-btn",
      styleVariant,
      `app-btn-${this.size || "md"}`,
      this.fullWidth ? "app-btn-full" : "",
      this.disabled || this.loading ? "app-btn-disabled" : "",
    ]
      .filter(Boolean)
      .join(" ");
  }
}

registerSchemaComponent("app-button", ButtonComponent);

<button
  appApplyTheme="app-button"
  [themedVariant]="buttonStyle"
  [themedSize]="size"
  [attr.type]="type || 'button'"
  [class]="getButtonClass()"
  [disabled]="disabled || loading"
  (click)="handleClick($event)"
  class="inline-flex items-center justify-center gap-2 rounded-lg border px-4 py-2 text-center font-medium transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
>
  @if (loading) {
    <span
      class="app-btn-spinner w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"
    ></span>
  } @else {
    @if (icon && iconPosition === "left") {
      <app-icon class="app-btn-icon" [icon]="icon" [size]="20" />
    }
    @if (label) {
      <span>{{ label }}</span>
    } @else {
      <ng-content></ng-content>
    }
    @if (icon && iconPosition === "right") {
      <app-icon class="app-btn-icon" [icon]="icon" [size]="20" />
    }
  }
</button>

// projects/ui/lit/button.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppButton = class AppButton extends LitElement {
  constructor() {
    super(...arguments);
    this.variant = "primary";
    this.size = "md";
    this.disabled = false;
    this.loading = false;
    this.icon = null;
    this.iconPosition = "left";
    this.fullWidth = false;
    this.type = "button";
  }
  static {
    this.styles = css`
      :host {
        display: inline-flex;
      }

      button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 0.5rem;
        border-radius: 0.5rem;
        border: 1px solid;
        padding: 0.5rem 1rem;
        text-align: center;
        font-weight: 500;
        transition: all 0.15s;
        cursor: pointer;
        border-width: 1px;
      }

      button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .app-btn-primary {
        border-color: var(--accent);
        background-color: var(--accent);
        color: var(--text-on-accent);
      }
      .app-btn-primary:hover {
        background-color: var(--accent-hover);
        border-color: var(--accent-hover);
      }

      .app-btn-secondary {
        border-color: var(--border-color);
        background-color: var(--bg-elevated);
        color: var(--text-primary);
      }
      .app-btn-secondary:hover {
        background-color: var(--bg-hover);
      }

      .app-btn-danger {
        border-color: var(--error);
        background-color: var(--error);
        color: var(--text-on-error);
      }
      .app-btn-danger:hover {
        opacity: 0.9;
      }

      .app-btn-warning {
        border-color: var(--warning);
        background-color: var(--warning);
        color: var(--text-on-warning);
      }
      .app-btn-warning:hover {
        opacity: 0.9;
      }

      .app-btn-success {
        border-color: var(--success);
        background-color: var(--success);
        color: var(--text-on-success);
      }
      .app-btn-success:hover {
        opacity: 0.9;
      }

      .app-btn-ghost {
        border-color: transparent;
        background-color: transparent;
        color: var(--text-secondary);
      }
      .app-btn-ghost:hover {
        background-color: var(--bg-hover);
        color: var(--text-primary);
      }

      .app-btn-sm {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
      }

      .app-btn-md {
        padding: 0.5rem 1rem;
        font-size: 1rem;
      }

      .app-btn-lg {
        padding: 0.75rem 1.5rem;
        font-size: 1.125rem;
      }

      .app-btn-full {
        width: 100%;
      }

      .app-btn-icon {
        font-size: 1.25rem;
      }

      .app-btn-spinner {
        width: 1rem;
        height: 1rem;
        border: 2px solid currentColor;
        border-top-color: transparent;
        border-radius: 50%;
        animation: spin 0.6s linear infinite;
      }

      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }
    `;
  }
  _handleClick(e) {
    if (this.disabled || this.loading) {
      e.preventDefault();
      e.stopPropagation();
      return;
    }
    this.dispatchEvent(
      new CustomEvent("click", { detail: e, bubbles: true, composed: true }),
    );
  }
  render() {
    const classes = [
      "app-btn",
      `app-btn-${this.variant}`,
      `app-btn-${this.size}`,
      this.fullWidth ? "app-btn-full" : "",
      this.disabled || this.loading ? "app-btn-disabled" : "",
    ]
      .filter(Boolean)
      .join(" ");
    return html`
      <button
        type="${this.type}"
        class="${classes}"
        ?disabled="${this.disabled || this.loading}"
        @click="${this._handleClick}"
      >
        ${this.loading
          ? html`<span class="app-btn-spinner"></span>`
          : html`
              ${this.icon && this.iconPosition === "left"
                ? html`<i class="material-icons app-btn-icon">${this.icon}</i>`
                : ""}
              <slot></slot>
              ${this.icon && this.iconPosition === "right"
                ? html`<i class="material-icons app-btn-icon">${this.icon}</i>`
                : ""}
            `}
      </button>
    `;
  }
};
__decorate([property()], AppButton.prototype, "variant", void 0);
__decorate([property()], AppButton.prototype, "size", void 0);
__decorate(
  [property({ type: Boolean })],
  AppButton.prototype,
  "disabled",
  void 0,
);
__decorate(
  [property({ type: Boolean })],
  AppButton.prototype,
  "loading",
  void 0,
);
__decorate([property()], AppButton.prototype, "icon", void 0);
__decorate([property()], AppButton.prototype, "iconPosition", void 0);
__decorate(
  [property({ type: Boolean })],
  AppButton.prototype,
  "fullWidth",
  void 0,
);
__decorate([property()], AppButton.prototype, "type", void 0);
AppButton = __decorate([customElement("app-button")], AppButton);
export { AppButton };
//# sourceMappingURL=button.js.map
