// projects/shared/src/components/empty-state/empty-state.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-empty-state",
  standalone: true,
  template: `
    <div class="icon-container" [class]="variant">
      @if (icon) {
        <span class="icon">{{ icon }}</span>
      }
    </div>
    @if (title) {
      <h3 class="title">{{ title }}</h3>
    }
    @if (message) {
      <p class="message">{{ message }}</p>
    }
    @if (action) {
      <div class="action">
        <button (click)="actionClicked.emit($event)">{{ action }}</button>
      </div>
    }
  `,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: center;
        padding: 2rem;
        gap: 1rem;
      }
      .icon-container {
        width: 64px;
        height: 64px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--bg-elevated);
        border: 2px solid var(--border-color);
      }
      .icon-container.danger {
        background: var(--error);
        border-color: var(--error);
      }
      .icon-container.success {
        background: var(--success);
        border-color: var(--success);
      }
      .icon {
        font-size: 2rem;
        width: 2rem;
        height: 2rem;
      }
      .icon-container.danger .icon,
      .icon-container.success .icon {
        color: var(--text-on-error);
      }
      .title {
        font-size: 1.5rem;
        font-weight: 600;
        color: var(--text-primary);
        margin: 0;
      }
      .message {
        font-size: 1rem;
        color: var(--text-secondary);
        margin: 0;
        max-width: 400px;
      }
      .action {
        margin-top: 0.5rem;
      }
      button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 0.5rem;
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        border: 1px solid var(--accent);
        background: var(--accent);
        color: var(--text-on-accent);
        font-weight: 500;
        cursor: pointer;
        transition: all 0.15s;
      }
      button:hover {
        background: var(--accent-hover);
        border-color: var(--accent-hover);
      }
    `,
  ],
})
export class EmptyStateComponent {
  @Input() title = "";
  @Input() message = "";
  @Input() icon = "";
  @Input() variant: "default" | "danger" | "success" = "default";
  @Input() action = "";
  @Output() actionClicked = new EventEmitter<Event>();
}

registerSchemaComponent("app-empty-state", EmptyStateComponent);

<div
  appApplyTheme="app-empty-state"
  class="w-16 h-16 rounded-full flex items-center justify-center border-2"
  [class]="variant"
  [class]="
    variant === 'danger'
      ? 'bg-[var(--error)] border-[var(--error)]'
      : variant === 'success'
        ? 'bg-[var(--success)] border-[var(--success)]'
        : 'bg-[var(--bg-elevated)] border-[var(--border-color)]'
  "
>
  @if (icon) {
    <span class="text-4xl size-8">{{ icon }}</span>
  }
</div>
@if (title) {
  <h3 class="text-2xl font-semibold m-0 text-[var(--text-primary)]">
    {{ title }}
  </h3>
}
@if (message) {
  <p class="text-base m-0 max-w-[400px] mt-2 text-[var(--text-secondary)]">
    {{ message }}
  </p>
}
@if (action) {
  <div class="mt-2">
    <button
      class="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-lg font-medium cursor-pointer transition-all duration-150 bg-[var(--accent)] border-[var(--accent)] text-[var(--text-on-accent)]"
      (mouseenter)="
        $any($event.target).style.background = 'var(--accent-hover)';
        $any($event.target).style.borderColor = 'var(--accent-hover)'
      "
      (mouseleave)="
        $any($event.target).style.background = 'var(--accent)';
        $any($event.target).style.borderColor = 'var(--accent)'
      "
      (click)="actionClicked.emit($event)"
    >
      {{ action }}
    </button>
  </div>
}

// projects/ui/lit/empty-state.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppEmptyState = class AppEmptyState extends LitElement {
    constructor() {
        super(...arguments);
        this.icon = null;
        this.title = "";
        this.message = "";
        this.actionLabel = null;
    }
    static { this.styles = css `
    :host {
      display: block;
    }

    .app-empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 2rem;
    }

    .app-empty-state-icon {
      font-size: 3.75rem;
      color: var(--text-muted);
      margin-bottom: 1rem;
    }

    .app-empty-state-title {
      font-size: 1.125rem;
      font-weight: 600;
      color: var(--text-primary);
      margin-bottom: 0.5rem;
    }

    .app-empty-state-message {
      font-size: 0.875rem;
      color: var(--text-secondary);
      margin-bottom: 1rem;
      max-width: 24rem;
    }

    .app-empty-state-action {
      padding: 0.5rem 1rem;
      border-radius: 0.5rem;
      background-color: var(--accent);
      color: var(--text-on-accent);
      font-size: 0.875rem;
      font-weight: 500;
      border: none;
      cursor: pointer;
      transition: opacity 0.15s;
    }
    .app-empty-state-action:hover {
      opacity: 0.9;
    }
  `; }
    _handleAction() {
        this.dispatchEvent(new CustomEvent("action", { bubbles: true, composed: true }));
    }
    render() {
        return html `
      <div class="app-empty-state">
        ${this.icon
            ? html `<i class="material-icons app-empty-state-icon"
              >${this.icon}</i
            >`
            : ""}
        ${this.title
            ? html `<h3 class="app-empty-state-title">${this.title}</h3>`
            : ""}
        ${this.message
            ? html `<p class="app-empty-state-message">${this.message}</p>`
            : ""}
        ${this.actionLabel
            ? html `
              <button
                class="app-empty-state-action"
                @click="${this._handleAction}"
              >
                ${this.actionLabel}
              </button>
            `
            : ""}
      </div>
    `;
    }
};
__decorate([
    property()
], AppEmptyState.prototype, "icon", void 0);
__decorate([
    property()
], AppEmptyState.prototype, "title", void 0);
__decorate([
    property()
], AppEmptyState.prototype, "message", void 0);
__decorate([
    property()
], AppEmptyState.prototype, "actionLabel", void 0);
AppEmptyState = __decorate([
    customElement("app-empty-state")
], AppEmptyState);
export { AppEmptyState };
//# sourceMappingURL=empty-state.js.map
