// projects/shared/src/components/progress-bar/progress-bar.component.ts
import { Component, Input } from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-progress-bar",
  standalone: true,
  template: `
    <div class="progress-container">
      <div
        [class]="'progress-fill ' + fillClass"
        [style.width.%]="percentage"
      ></div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
      .progress-container {
        width: 100%;
        height: 0.5rem;
        background-color: var(--bg-elevated);
        border-radius: 0.25rem;
        overflow: hidden;
        border: 1px solid var(--border-color);
      }
      .progress-fill {
        height: 100%;
        border-radius: 0.25rem;
        transition: width 0.3s ease;
      }
      .progress-fill.low {
        background-color: var(--warning);
      }
      .progress-fill.medium {
        background-color: var(--accent);
      }
      .progress-fill.high {
        background-color: var(--success);
      }
    `,
  ],
})
export class ProgressBarComponent {
  @Input() value = 0;
  @Input() max = 100;

  get percentage(): number {
    return (this.value / this.max) * 100;
  }

  get fillClass(): string {
    const pct = this.percentage;
    if (pct < 40) return "low";
    if (pct < 75) return "medium";
    return "high";
  }
}

registerSchemaComponent("app-progress-bar", ProgressBarComponent);

<div
  appApplyTheme="app-progress-bar"
  class="w-full h-2 bg-[var(--bg-elevated)] rounded border border-[var(--border-color)] overflow-hidden"
>
  <div
    class="h-full rounded transition-all duration-300"
    [class.bg-[var(--warning)]]="fillClass === 'low'"
    [class.bg-[var(--accent)]]="fillClass === 'medium'"
    [class.bg-[var(--success)]]="fillClass === 'high'"
    [style.width.%]="percentage"
  ></div>
</div>

// projects/ui/lit/progress-bar.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppProgressBar = class AppProgressBar extends LitElement {
    percentage = 0;
    showLabel = false;
    static styles = css `
    :host {
      display: block;
    }

    .app-progress-bar {
      @apply flex items-center gap-2;
    }

    .app-progress-bar-track {
      @apply flex-1 h-2 rounded-full bg-[var(--bg-tertiary)] overflow-hidden;
    }

    .app-progress-bar-fill {
      @apply h-full rounded-full bg-[var(--accent)] transition-all duration-300;
    }

    .app-progress-bar-label {
      @apply text-xs text-[var(--text-secondary)] font-medium min-w-10 text-right;
    }
  `;
    get clampedPercentage() {
        return Math.min(100, Math.max(0, this.percentage));
    }
    render() {
        return html `
      <div class="app-progress-bar">
        <div class="app-progress-bar-track">
          <div
            class="app-progress-bar-fill"
            style="width: ${this.clampedPercentage}%"
          ></div>
        </div>
        ${this.showLabel
            ? html `<span class="app-progress-bar-label"
              >${this.clampedPercentage}%</span
            >`
            : ""}
      </div>
    `;
    }
};
__decorate([
    property({ type: Number })
], AppProgressBar.prototype, "percentage", void 0);
__decorate([
    property({ type: Boolean })
], AppProgressBar.prototype, "showLabel", void 0);
AppProgressBar = __decorate([
    customElement("app-progress-bar")
], AppProgressBar);
export { AppProgressBar };
//# sourceMappingURL=progress-bar.js.map
