// projects/shared/src/components/switch/switch.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-switch",
  standalone: true,
  template: `
    <label class="switch" [class.switch-checked]="checked">
      <input
        type="checkbox"
        [checked]="checked"
        [disabled]="disabled"
        (change)="handleChange($event)"
      />
      <span class="slider"></span>
      @if (label) {
        <span class="switch-label">{{ label }}</span>
      }
    </label>
  `,
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
      }
      .switch {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        cursor: pointer;
        position: relative;
      }
      .switch input {
        position: absolute;
        opacity: 0;
        width: 0;
        height: 0;
      }
      .slider {
        width: 2.5rem;
        height: 1.25rem;
        background-color: var(--border-color);
        border-radius: 1rem;
        transition: background-color 0.2s;
        position: relative;
      }
      .slider::before {
        content: "";
        position: absolute;
        width: 1rem;
        height: 1rem;
        left: 2px;
        top: 2px;
        background-color: white;
        border-radius: 50%;
        transition: transform 0.2s;
      }
      .switch-checked .slider {
        background-color: var(--accent);
      }
      .switch-checked .slider::before {
        transform: translateX(1.25rem);
      }
      .switch-label {
        color: var(--text-primary);
        font-size: 0.875rem;
        user-select: none;
      }
      input:disabled ~ .slider {
        opacity: 0.5;
        cursor: not-allowed;
      }
    `,
  ],
})
export class SwitchComponent {
  @Input() checked = false;
  @Input() label = "";
  @Input() disabled = false;
  @Output() changed = new EventEmitter<boolean>();

  handleChange(e: Event) {
    this.changed.emit((e.target as HTMLInputElement).checked);
  }
}

registerSchemaComponent("app-switch", SwitchComponent);

<label
  appApplyTheme="app-switch"
  class="switch flex items-center gap-2 cursor-pointer relative"
  [class.switch-checked]="checked"
  [class.bg-[var(--accent)]]="checked"
>
  <input
    type="checkbox"
    [checked]="checked"
    [disabled]="disabled"
    (change)="handleChange($event)"
    class="absolute opacity-0 w-0 h-0"
  />
  <span
    class="slider w-10 h-5 rounded-full transition-colors relative"
    style="background-color: var(--border-color)"
  ></span>
  @if (label) {
    <span class="switch-label text-sm select-none text-[var(--text-primary)]">{{
      label
    }}</span>
  }
</label>

// projects/ui/lit/switch.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppSwitch = class AppSwitch extends LitElement {
    disabled = false;
    checked = false;
    static styles = css `
    :host {
      display: inline-flex;
    }

    .app-switch {
      @apply w-11 h-6 rounded-full border-2 border-[var(--border-color)] cursor-pointer;
      @apply transition-all relative;
      background: transparent;
      border-style: solid;
    }

    .app-switch-checked {
      @apply bg-[var(--accent)] border-[var(--accent)];
    }

    .app-switch-disabled {
      @apply opacity-50 cursor-not-allowed;
    }

    .app-switch-thumb {
      @apply absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform;
    }

    .app-switch-checked .app-switch-thumb {
      transform: translateX(20px);
    }
  `;
    _toggle() {
        if (this.disabled)
            return;
        this.checked = !this.checked;
        this.dispatchEvent(new CustomEvent("checked-change", {
            detail: this.checked,
            bubbles: true,
            composed: true,
        }));
    }
    render() {
        return html `
      <div
        class="app-switch ${this.checked ? "app-switch-checked" : ""} ${this
            .disabled
            ? "app-switch-disabled"
            : ""}"
        @click="${this._toggle}"
      >
        <span class="app-switch-thumb"></span>
      </div>
    `;
    }
};
__decorate([
    property({ type: Boolean })
], AppSwitch.prototype, "disabled", void 0);
__decorate([
    property({ type: Boolean })
], AppSwitch.prototype, "checked", void 0);
AppSwitch = __decorate([
    customElement("app-switch")
], AppSwitch);
export { AppSwitch };
//# sourceMappingURL=switch.js.map
