// projects/shared/src/components/tooltip/tooltip.component.ts
import { Component, Input } from "@angular/core";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-tooltip",
  standalone: true,
  template: `
    <div
      class="tooltip-trigger"
      (mouseenter)="show = true"
      (mouseleave)="show = false"
      (focus)="show = true"
      (blur)="show = false"
      tabindex="0"
    >
      <ng-content></ng-content>
      @if (show) {
        <div class="tooltip-bubble" [class]="position || 'top'">{{ text }}</div>
      }
    </div>
  `,
  styles: [
    `
      :host {
        display: inline-flex;
        position: relative;
      }
      .tooltip-trigger {
        display: inline-flex;
        position: relative;
        cursor: pointer;
      }
      .tooltip-bubble {
        position: absolute;
        z-index: 1000;
        padding: 0.375rem 0.75rem;
        border-radius: 0.375rem;
        background: var(--bg-elevated);
        color: var(--text-primary);
        font-size: 0.75rem;
        white-space: nowrap;
        border: 1px solid var(--border-color);
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        pointer-events: none;
      }
      .tooltip-bubble.top {
        bottom: 100%;
        left: 50%;
        transform: translateX(-50%);
        margin-bottom: 0.5rem;
      }
      .tooltip-bubble.bottom {
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        margin-top: 0.5rem;
      }
      .tooltip-bubble.left {
        right: 100%;
        top: 50%;
        transform: translateY(-50%);
        margin-right: 0.5rem;
      }
      .tooltip-bubble.right {
        left: 100%;
        top: 50%;
        transform: translateY(-50%);
        margin-left: 0.5rem;
      }
    `,
  ],
})
export class TooltipComponent {
  @Input() text = "";
  @Input() position: "top" | "bottom" | "left" | "right" = "top";
  @Input() delay = 200;
  show = false;
}

registerSchemaComponent("app-tooltip", TooltipComponent);

<div
  appApplyTheme="app-tooltip"
  class="inline-flex relative cursor-pointer"
  (mouseenter)="show = true"
  (mouseleave)="show = false"
  (focus)="show = true"
  (blur)="show = false"
  tabindex="0"
>
  <ng-content></ng-content>
  @if (show) {
    <div
      class="absolute z-50 px-3 py-1.5 rounded-md text-xs whitespace-nowrap shadow-md pointer-events-none tooltip-bubble bg-[var(--bg-elevated)] text-[var(--text-primary)] border border-[var(--border-color)]"
      [class.top]="!position || position === 'top'"
      [class.bottom]="position === 'bottom'"
      [class.left]="position === 'left'"
      [class.right]="position === 'right'"
    >
      {{ text || content }}
    </div>
  }
</div>

// projects/ui/lit/tooltip.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
let AppTooltip = class AppTooltip extends LitElement {
  constructor() {
    super(...arguments);
    this.content = "";
    this.position = "top";
    this.show = false;
  }
  static {
    this.styles = css`
      :host {
        display: inline-block;
      }

      .app-tooltip-wrapper {
        position: relative;
        display: inline-block;
      }

      .app-tooltip {
        position: absolute;
        z-index: 50;
        padding: 0.25rem 0.5rem;
        font-size: 0.75rem;
        background-color: var(--bg-elevated);
        color: var(--text-primary);
        border-radius: 0.25rem;
        box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1);
        white-space: nowrap;
      }

      .app-tooltip-top {
        bottom: 100%;
        left: 50%;
        transform: translateX(-50%);
        margin-bottom: 0.5rem;
      }

      .app-tooltip-bottom {
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        margin-top: 0.5rem;
      }

      .app-tooltip-left {
        right: 100%;
        top: 50%;
        transform: translateY(-50%);
        margin-right: 0.5rem;
      }

      .app-tooltip-right {
        left: 100%;
        top: 50%;
        transform: translateY(-50%);
        margin-left: 0.5rem;
      }
    `;
  }
  render() {
    return html`
      <div class="app-tooltip-wrapper">
        <slot></slot>
        ${this.show
          ? html`
              <div class="app-tooltip app-tooltip-${this.position}">
                ${this.content}
              </div>
            `
          : ""}
      </div>
    `;
  }
};
__decorate([property()], AppTooltip.prototype, "content", void 0);
__decorate([property()], AppTooltip.prototype, "position", void 0);
__decorate([property({ type: Boolean })], AppTooltip.prototype, "show", void 0);
AppTooltip = __decorate([customElement("app-tooltip")], AppTooltip);
export { AppTooltip };
//# sourceMappingURL=tooltip.js.map
