// projects/shared/src/components/pagination/pagination.component.ts
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("app-pagination")
export class AppPagination extends LitElement {
  @property({ type: Number }) declare page: number;
  @property({ type: Number }) declare total: number;
  @property({ type: Number }) declare pageSize: number;
  constructor() {
    super();
    for (const key of ["page", "total", "pageSize"]) {
      if (Object.prototype.hasOwnProperty.call(this, key)) {
        const val = (this as Record<string, unknown>)[key];
        delete (this as Record<string, unknown>)[key];
        (this as Record<string, unknown>)[key] = val;
      }
    }
  }

  override connectedCallback(): void {
    const saved: Record<string, unknown> = {};
    for (const key of ["page", "total", "pageSize"]) {
      if (Object.prototype.hasOwnProperty.call(this, key)) {
        saved[key] = (this as Record<string, unknown>)[key];
        delete (this as Record<string, unknown>)[key];
      }
    }
    super.connectedCallback();
    for (const [key, value] of Object.entries(saved)) {
      (this as Record<string, unknown>)[key] = value;
    }
  }


  static override styles = css`
    :host {
      display: block;
    }

    .pagination {
      display: inline-flex;
      align-items: center;
      gap: 0.25rem;
    }

    button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: 2rem;
      height: 2rem;
      padding: 0 0.5rem;
      border: 1px solid var(--border-color);
      border-radius: 0.375rem;
      background-color: var(--bg-elevated);
      color: var(--text-primary);
      font-size: 0.875rem;
      cursor: pointer;
      transition: background-color 0.15s;
    }

    button:hover:not(:disabled) {
      background-color: var(--bg-hover);
    }

    button:disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }

    button.active {
      background-color: var(--accent);
      border-color: var(--accent);
      color: var(--text-on-accent);
    }

    .ellipsis {
      padding: 0 0.25rem;
      color: var(--text-secondary);
    }
  `;

  private get _totalPages(): number {
    return Math.ceil(this.total / this.pageSize);
  }

  private _goTo(page: number) {
    if (page < 1 || page > this._totalPages || page === this.page) return;
    this.dispatchEvent(
      new CustomEvent("pageChange", { detail: { page }, bubbles: true, composed: true }),
    );
  }

  private _getPageNumbers(): (number | "...")[] {
    const total = this._totalPages;
    const current = this.page;
    if (total <= 7) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }
    const pages: (number | "...")[] = [];
    if (current <= 4) {
      for (let i = 1; i <= 5; i++) pages.push(i);
      pages.push("...");
      pages.push(total);
    } else if (current >= total - 3) {
      pages.push(1);
      pages.push("...");
      for (let i = total - 4; i <= total; i++) pages.push(i);
    } else {
      pages.push(1);
      pages.push("...");
      pages.push(current - 1);
      pages.push(current);
      pages.push(current + 1);
      pages.push("...");
      pages.push(total);
    }
    return pages;
  }

  override render() {
    const total = this._totalPages;
    if (total <= 1) return html``;

    return html`
      <div class="pagination">
        <button @click="${() => this._goTo(this.page - 1)}" ?disabled="${this.page === 1}">
          ‹
        </button>
        ${this._getPageNumbers().map((p) =>
          p === "..."
            ? html`<span class="ellipsis">…</span>`
            : html`<button
                class="${p === this.page ? "active" : ""}"
                @click="${() => this._goTo(p)}"
              >
                ${p}
              </button>`,
        )}
        <button @click="${() => this._goTo(this.page + 1)}" ?disabled="${this.page === total}">
          ›
        </button>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "app-pagination": AppPagination;
  }
}
<div
  class="flex w-full items-center justify-between border-t border-[var(--border-subtle)] bg-transparent px-6 py-3"
>
  <div class="flex items-center gap-6">
    <span class="text-sm text-[var(--text-dim)]">
      Showing
      <span class="font-bold text-[var(--text-main)]">{{ startIndex }}</span
      >-<span class="font-bold text-[var(--text-main)]">{{ endIndex }}</span> of
      <span class="font-bold text-[var(--text-main)]">{{ totalItems }}</span>
    </span>
    <div class="flex items-center gap-3">
      <span class="text-xs text-[var(--text-muted)]">Rows per page:</span>
      <select
        class="cursor-pointer rounded-lg border border-[var(--border-visible)] bg-[var(--bg-card)] px-3 py-1.5 text-sm text-[var(--text-main)] focus:border-[var(--accent)] focus:outline-none"
        [value]="pageSize"
        (change)="onPageSizeChange(+$any($event.target).value)"
      >
        <option value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
      </select>
    </div>
  </div>

  <div class="flex items-center gap-2">
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasPrevPage"
      (click)="firstPage()"
      title="First page"
    >
      <app-icon icon="first_page" [size]="18" />
    </button>
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasPrevPage"
      (click)="prevPage()"
      title="Previous page"
    >
      <app-icon icon="chevron_left" [size]="18" />
    </button>
    <span class="px-3 text-sm text-[var(--text-dim)]"
      >Page {{ currentPage + 1 }} of {{ totalPages || 1 }}</span
    >
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasNextPage"
      (click)="nextPage()"
      title="Next page"
    >
      <app-icon icon="chevron_right" [size]="18" />
    </button>
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasNextPage"
      (click)="lastPage()"
      title="Last page"
    >
      <app-icon icon="last_page" [size]="18" />
    </button>
  </div>
</div>

// projects/shared/src/core/lib/pagination/pagination.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
} from "@angular/core";
import { MatIconModule } from "@angular/material/icon";
@Component({
  selector: "app-pagination",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatIconModule],
  templateUrl: "./pagination.component.html",
})
export class PaginationComponent {
  constructor(private cdr: ChangeDetectorRef) {}
  @Input() totalItems = 0;
  @Input() currentPage = 0;
  @Input() pageSize = 50;
  @Output() pageChange = new EventEmitter<number>();
  @Output() pageSizeChange = new EventEmitter<number>();
  get totalPages(): number {
    return Math.ceil(this.totalItems / this.pageSize) || 1;
  }
  get hasNextPage(): boolean {
    return this.currentPage < this.totalPages - 1;
  }
  get hasPrevPage(): boolean {
    return this.currentPage > 0;
  }
  get startIndex(): number {
    return this.currentPage * this.pageSize + 1;
  }
  get endIndex(): number {
    return Math.min((this.currentPage + 1) * this.pageSize, this.totalItems);
  }
  nextPage() {
    if (this.hasNextPage) {
      this.pageChange.emit(this.currentPage + 1);
    }
  }
  prevPage() {
    if (this.hasPrevPage) {
      this.pageChange.emit(this.currentPage - 1);
    }
  }
  firstPage() {
    this.pageChange.emit(0);
  }
  lastPage() {
    this.pageChange.emit(this.totalPages - 1);
  }
  onPageSizeChange(size: number) {
    this.pageSizeChange.emit(size);
    this.pageChange.emit(0);
  }
}

<div
  class="flex w-full items-center justify-between border-t border-[var(--border-subtle)] bg-transparent px-6 py-3"
>
  <div class="flex items-center gap-6">
    <span class="text-sm text-[var(--text-dim)]">
      Showing
      <span class="font-bold text-[var(--text-main)]">{{ startIndex }}</span
      >-<span class="font-bold text-[var(--text-main)]">{{ endIndex }}</span> of
      <span class="font-bold text-[var(--text-main)]">{{ totalItems }}</span>
    </span>
    <div class="flex items-center gap-3">
      <span class="text-xs text-[var(--text-muted)]">Rows per page:</span>
      <select
        class="cursor-pointer rounded-lg border border-[var(--border-visible)] bg-[var(--bg-card)] px-3 py-1.5 text-sm text-[var(--text-main)] focus:border-[var(--accent)] focus:outline-none"
        [value]="pageSize"
        (change)="onPageSizeChange(+$any($event.target).value)"
      >
        <option value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
      </select>
    </div>
  </div>

  <div class="flex items-center gap-2">
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasPrevPage"
      (click)="firstPage()"
      title="First page"
    >
      <mat-icon fontIcon="first_page" class="!text-base"></mat-icon>
    </button>
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasPrevPage"
      (click)="prevPage()"
      title="Previous page"
    >
      <mat-icon fontIcon="chevron_left" class="!text-base"></mat-icon>
    </button>
    <span class="px-3 text-sm text-[var(--text-dim)]"
      >Page {{ currentPage + 1 }} of {{ totalPages || 1 }}</span
    >
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasNextPage"
      (click)="nextPage()"
      title="Next page"
    >
      <mat-icon fontIcon="chevron_right" class="!text-base"></mat-icon>
    </button>
    <button
      class="rounded-lg p-2 text-[var(--text-dim)] transition-all hover:bg-[var(--bg-card)] hover:text-[var(--text-main)] disabled:cursor-not-allowed disabled:opacity-30"
      [disabled]="!hasNextPage"
      (click)="lastPage()"
      title="Last page"
    >
      <mat-icon fontIcon="last_page" class="!text-base"></mat-icon>
    </button>
  </div>
</div>
