// projects/ui/lit/input.js
import { __decorate } from "tslib";
import { LitElement, html, css } from "lit";
import { customElement, property, state } from "lit/decorators.js";
let AppInput = class AppInput extends LitElement {
    type = "text";
    placeholder = "";
    label = null;
    disabled = false;
    error = null;
    icon = null;
    _value = "";
    _focused = false;
    static styles = css `
    :host {
      display: block;
    }

    .app-input-wrapper {
      @apply flex flex-col gap-1;
    }

    .app-input-label {
      @apply text-sm font-medium text-[var(--text-primary)];
    }

    .app-input-container {
      @apply relative flex items-center;
    }

    .app-input {
      @apply w-full px-3 py-2 rounded-lg border bg-[var(--bg-primary)] text-[var(--text-primary)];
      @apply placeholder:text-[var(--text-muted)];
      @apply transition-all outline-none;
      border: 1px solid var(--border-color);
      box-sizing: border-box;
    }

    .app-input:focus {
      @apply border-[var(--accent)] ring-1 ring-[var(--accent)];
    }

    .app-input-default:focus {
      @apply border-[var(--accent)] ring-1 ring-[var(--accent)];
    }

    .app-input-error {
      @apply border-[var(--error)] ring-1 ring-[var(--error)];
    }

    .app-input-with-icon {
      @apply pl-10;
    }

    .app-input-icon {
      @apply absolute left-3 text-[var(--text-muted)] text-xl;
    }

    .app-input-focused .app-input-icon {
      @apply text-[var(--accent)];
    }

    .app-input:disabled {
      @apply opacity-50 cursor-not-allowed bg-[var(--bg-tertiary)];
    }

    .app-input-error-text {
      @apply text-xs text-[var(--error)];
    }
  `;
    _handleInput(e) {
        const target = e.target;
        this._value = target.value;
        this.dispatchEvent(new CustomEvent("input", {
            detail: this._value,
            bubbles: true,
            composed: true,
        }));
    }
    _handleFocus() {
        this._focused = true;
    }
    _handleBlur() {
        this._focused = false;
        this.dispatchEvent(new CustomEvent("blur", { bubbles: true, composed: true }));
    }
    render() {
        const stateClass = this.error ? "app-input-error" : "app-input-default";
        const classes = [
            "app-input",
            stateClass,
            this.icon ? "app-input-with-icon" : "",
        ]
            .filter(Boolean)
            .join(" ");
        return html `
      <div class="app-input-wrapper">
        ${this.label
            ? html `<label class="app-input-label">${this.label}</label>`
            : ""}
        <div
          class="app-input-container ${this._focused
            ? "app-input-focused"
            : ""}"
        >
          ${this.icon
            ? html `<i class="material-icons app-input-icon">${this.icon}</i>`
            : ""}
          <input
            type="${this.type}"
            class="${classes}"
            placeholder="${this.placeholder}"
            ?disabled="${this.disabled}"
            .value="${this._value}"
            @input="${this._handleInput}"
            @focus="${this._handleFocus}"
            @blur="${this._handleBlur}"
          />
        </div>
        ${this.error
            ? html `<span class="app-input-error-text">${this.error}</span>`
            : ""}
      </div>
    `;
    }
};
__decorate([
    property()
], AppInput.prototype, "type", void 0);
__decorate([
    property()
], AppInput.prototype, "placeholder", void 0);
__decorate([
    property()
], AppInput.prototype, "label", void 0);
__decorate([
    property({ type: Boolean })
], AppInput.prototype, "disabled", void 0);
__decorate([
    property()
], AppInput.prototype, "error", void 0);
__decorate([
    property()
], AppInput.prototype, "icon", void 0);
__decorate([
    state()
], AppInput.prototype, "_value", void 0);
__decorate([
    state()
], AppInput.prototype, "_focused", void 0);
AppInput = __decorate([
    customElement("app-input")
], AppInput);
export { AppInput };
//# sourceMappingURL=input.js.map

// projects/shared/src/components/input/input.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { MatIconModule } from "@angular/material/icon";
import { registerSchemaComponent } from "../../core/lib/schema-component.registry";

@Component({
  selector: "app-input",
  standalone: true,
  imports: [MatIconModule],
  template: `
    <div class="app-input-wrapper">
      @if (label) {
        <label class="app-input-label">{{ label }}</label>
      }
      <div class="app-input-container" [class.app-input-focused]="focused">
        @if (icon) {
          <mat-icon class="app-input-icon" [fontIcon]="icon" />
        }
        <input
          #inputEl
          [attr.type]="type"
          class="app-input"
          [class.app-input-with-icon]="!!icon"
          [class.app-input-error]="!!error"
          [placeholder]="placeholder"
          [disabled]="disabled"
          [value]="value"
          (input)="handleInput($event)"
          (focus)="focused = true"
          (blur)="focused = false"
        />
      </div>
      @if (error) {
        <span class="app-input-error-text">{{ error }}</span>
      }
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
      .app-input-wrapper {
        display: flex;
        flex-direction: column;
        gap: 0.25rem;
      }
      .app-input-label {
        font-size: 0.875rem;
        font-weight: 500;
        color: var(--text-primary);
      }
      .app-input-container {
        position: relative;
        display: flex;
        align-items: center;
      }
      .app-input {
        width: 100%;
        padding: 0.5rem 0.75rem;
        border-radius: 0.5rem;
        border: 1px solid var(--border-color);
        background-color: var(--bg-primary);
        color: var(--text-primary);
        box-sizing: border-box;
        transition: all 0.15s;
        outline: none;
      }
      .app-input::placeholder {
        color: var(--text-muted);
      }
      .app-input:focus {
        border-color: var(--accent);
        box-shadow: 0 0 0 1px var(--accent);
      }
      .app-input-error {
        border-color: var(--error);
        box-shadow: 0 0 0 1px var(--error);
      }
      .app-input-with-icon {
        padding-left: 2.5rem;
      }
      .app-input-icon {
        position: absolute;
        left: 0.75rem;
        font-size: 1.25rem;
        color: var(--text-muted);
      }
      .app-input-focused .app-input-icon {
        color: var(--accent);
      }
      .app-input:disabled {
        opacity: 0.5;
        cursor: not-allowed;
        background-color: var(--bg-tertiary);
      }
      .app-input-error-text {
        font-size: 0.75rem;
        color: var(--error);
      }
    `,
  ],
})
export class InputComponent {
  @Input() type = "text";
  @Input() placeholder = "";
  @Input() label = "";
  @Input() icon = "";
  @Input() disabled = false;
  @Input() value = "";
  @Input() error = "";
  @Output() input = new EventEmitter<string>();
  @Output() blurred = new EventEmitter<void>();
  focused = false;

  handleInput(e: Event) {
    this.value = (e.target as HTMLInputElement).value;
    this.input.emit(this.value);
  }
}

registerSchemaComponent("app-input", InputComponent);

<div appApplyTheme="app-input" class="flex flex-col gap-1">
  @if (label) {
    <label class="text-sm font-medium text-[var(--text-primary)]">{{
      label
    }}</label>
  }
  <div class="relative flex items-center" [class.app-input-focused]="focused">
    @if (icon) {
      <app-icon
        class="absolute left-3 text-xl"
        [icon]="icon"
        [size]="20"
        [class]="focused ? 'text-[var(--accent)]' : 'text-[var(--text-muted)]'"
      />
    }
    <input
      #inputEl
      [attr.type]="type"
      class="w-full px-3 py-2 rounded-lg border transition-all outline-none focus:shadow-[0_0_0_1px_var(--accent)] disabled:opacity-50 disabled:cursor-not-allowed"
      [class.ps-10]="!!icon"
      [class.border-[var(--error)]]="error"
      [class.border-[var(--accent)]]="!error && focused"
      [class.border-[var(--border-color)]]="!error && !focused"
      [class.bg-[var(--bg-tertiary)]]="disabled"
      [class.bg-[var(--bg-primary)]]="!disabled"
      [placeholder]="placeholder"
      [disabled]="disabled"
      [value]="value"
      (input)="handleInput($event)"
      (focus)="focused = true"
      (blur)="focused = false"
    />
  </div>
  @if (error) {
    <span class="text-xs text-[var(--error)]">{{ error }}</span>
  }
</div>
